export const FETCH_UNIT_REQUEST = "FETCH_UNIT_REQUEST";
export const FETCH_UNIT_SUCCESS = "FETCH_UNIT_SUCCESS";
export const FETCH_UNIT_FAILURE = "FETCH_UNIT_FAILURE";
export const FILTER_UNIT = "FILTER_UNIT";
